game-board:
  games:
    game1:
      gameId: "game1"
      currentStatus: PREPARE
      bettingTime: 20
      rollingTime: 3
      calculatingTime: 2
      rollingResult: UNKNOWN
      usersOnGame: {}
    game2:
      gameId: "game2"
      currentStatus: PREPARE
      bettingTime: 20
      rollingTime: 3
      calculatingTime: 2
      rollingResult: UNKNOWN
      usersOnGame: {}
    game3:
      gameId: "game3"
      currentStatus: PREPARE
      bettingTime: 20
      rollingTime: 3
      calculatingTime: 2
      rollingResult: UNKNOWN
      usersOnGame: { }